---
  - name: Create RKE2 Directory
    file:
       path: "{{ confdir }}"
       state: directory
       owner: root
       group: root
       mode: '0770'
       recurse: yes

  - name: Installing RKE2 Agent on Workers
    shell: |
        curl -sfL https://get.rke2.io |  INSTALL_RKE2_TYPE=agent sh -

  - name: Copy Master Rancher Config file
    copy:
     src: /tmp/rke2_{{ clustername }}_config.yaml
     dest: /etc/rancher/rke2/config.yaml
     owner: root
     group: root
     mode: '0660'

  - name: Start rke2-agent service
    service:
      name: rke2-agent
      state: started
      enabled: yes 
  
  - name: Simlink kubectl
    shell: |
      ln -s $(find /var/lib/rancher/rke2/data/ -name kubectl) /usr/local/bin/kubectl
    ignore_errors: yes
  
  - name: Append /var/lib/rancher/rke2/bin/ to PATH env
    lineinfile:
      path: /root/.bash_profile
      line: export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
      create: yes
      backup: yes


