---
    - name: Install HELM v3
      shell: 'curl -sLk raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sh'
      ignore_errors: yes
   
    - name: Add Helm Repository
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "{{ helm_repo }}"
    
    - name: Add jetstack Repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "{{ jetstack_repo }}"
    
    - name: Add cert-manager CRD
      shell: |
          kubectl apply -f {{ cert_manager }}
    - name: Show python install in use
      debug:
       var: ansible_python
    
    - name: Installing Jetstack
      kubernetes.core.helm:
          name: cert-manager
          chart_ref: jetstack/cert-manager
          release_namespace: cert-manager
          create_namespace: true
          update_repo_cache: yes 
          disable_hook: true
          wait_timeout: 30s
   
    - name: Installing Rancher UI
      kubernetes.core.helm:
       name: rancher
       chart_ref: rancher-stable/rancher
       release_namespace: cattle-system
       create_namespace: yes
       update_repo_cache: yes    
       values:
        replicas: 1
        hostname: "{{ rancher_domain }}"
        bootstrapPassword: "{{ rancher_password }}"
  
